### ISSUE TITLE
Can't  create project?

### ISSUE THREAD

**Issue by crossle** [jgilfelt/android-adt-templates#2]
error tip

 This template requires a more recent version of the Android Eclipse plugin. Please update from version 20.0.3.

**Comment by crossle** [comment]
path: android-sdk-linux/tools/templates/activities/*

**Comment by naddaf** [comment]
Same issue here; the docs says version 20 or above of ADT would work but mine which is 20.0.3 gives the same error; I do see the templates but due to the above mentioned error, it doesn't let me create a project. Do we need to get the preview version of ADT?

**Comment by rciovati** [comment]
From what i can see from ADT code, set `format="1"` inside `template.xml` should solve this because`format="3"` looks be supported just from ADT21.

**Comment by crossle** [comment]
thks @rciovati  , mofidy from `format="3"`to `format="1"`, it's avaible

update ADT21 , it's preview
https://dl-ssl.google.com/android/eclipse-preview/

I try update ADT to 21 , it's resolved

**Comment by jgilfelt** [comment]
Thanks and sorry about the confusion. I will update the documentation accordingly.
