### ISSUE TITLE
Error when opening activity_date_list.xml

### ISSUE THREAD

**Issue by ErnestG** [jgilfelt/android-adt-templates#7]
When I open up "activity_date_list.xml" or "activity_date_twopane.xml" I get an error in the XML from eclipse. I ran the app perfectly, but when I opened those two files I automatically recieved errors on this line:

```
tools:layout="@android:layout/list_content" 
```

Any ideas?

**Comment by jgilfelt** [comment]
Please remove those lines. It looks like the new Lint checks in the latest tools dont like `@android:layout/list_content` when your minSdkVersion is below 11 despite that resource being available. The `tools:layout` attribute is only used by the Eclipse layout editor and is ignored at runtime so I'm not sure why Lint want's to validate them.
